- name: Install mysql-server 
  hosts: DB
  become: yes
  vars:
    my_sql_pass: ExpenseApp@1
    my_sql_host: 34.239.104.189
  tasks:
  - name: Installing mysql on DB-server instance
    ansible.builtin.package:
      name: mysql-server
      state: present
  - name: Starting mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: change root password for mysql
    ansible.builtin.command: mysql_secure_installation --set-root-pass "{{my_sql_pass}}"

  - name: installing pymysql 
    ansible.builtin.pip:
      name:
      - pymysql
      executable: pip3.9
  - name: connect to mysql
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{my_sql_pass}}"
      login_host: "{{my_sql_host}}"
    ignore_errors: true
    register: mysql_info
  - name: printing mysql login info
    ansible.builtin.debug:
      msg: "{{mysql_info}}"