- name: Install mysql-server 
  hosts: DB
  become: yes
  vars:
    my_sql_pass: "ExpenseApp@1"
  tasks:
  - name: Installing mysql on DB-server instance
    ansible.builtin.package:
      name: mysql-server
      state: present
  - name: Starting mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: change root password for mysql
    ansible.builtin.command: mysql_secure_installation --set-root-pass "{{my_sql_pass}}"