- name: Configuring web server
  hosts: web
  become: yes
  tasks:
  - name: Installing nginx
    ansible.builtin.package:
      name: nginx
      state: present
  
  - name: start nginx server
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  
  - name: Remve html content in nginx
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent

  - name: Create html dir 
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: present
  
  - name: Download application code 
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip
  
  - name: Extract the code into html directory
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html/
      remote_src: yes
  
  - name: copy expense conf
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted